Algoritmo "Area_circulo"
// Disciplina   : Algoritimos
// Professor   : Jailson Santos 
// Descrição   : Este rograma calcula a area de uma circunferencia e
//imprime o resultado na tel
// Autor(a)    : Bianca Cristina
// Data atual  : 06/09/2020
Var
// Seção de Declarações das variáveis 
A= real R= real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  leia R
  A<- 3.114159*R^2
  escreva A

Fimalgoritmo