Algoritmo "Raiz quadrada 15 à 200"
//
// Disciplina : Algoritimo
// Descrição   : Este programa calcula a raiz quadrada dos numeros de 15 à 200
// Autor(a)    : Bianca Cristina
// Data atual  : 27/10/2020
Var
// Seção de Declarações das variáveis 
   contador:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  contador<-contador+15
enquanto contador<201 faca

escreval(contador," = ",contador*contador)
contador<-contador+1
fimenquanto

Fimalgoritmo